ci:
  autoupdate_schedule: quarterly
repos:
  - repo: https://github.com/Quantco/pre-commit-mirrors-nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout-conda
        exclude: ^niceplots/deprecated/
  - repo: https://github.com/Quantco/pre-commit-mirrors-black
    rev: 23.11.0
    hooks:
      - id: black-conda
        exclude: ^niceplots/deprecated/
        args:
          - --safe
          - --target-version=py311
  - repo: https://github.com/Quantco/pre-commit-mirrors-ruff
    rev: 0.1.6
    hooks:
      - id: ruff-conda
        exclude: ^niceplots/deprecated/
  - repo: https://github.com/Quantco/pre-commit-mirrors-mypy
    rev: 1.7.1
    hooks:
      - id: mypy-conda
        exclude: ^niceplots/deprecated/
        additional_dependencies:
          - -c
          - conda-forge
          - types-setuptools
          - types-PyYAML
          - types-toml
  - repo: https://github.com/Quantco/pre-commit-mirrors-prettier
    rev: 3.1.0
    hooks:
      - id: prettier-conda
        files: "\\.(md|yml|yaml)$"
        exclude: ^niceplots/deprecated/
  - repo: https://github.com/Quantco/pre-commit-mirrors-pre-commit-hooks
    rev: 4.4.0
    hooks:
      - id: trailing-whitespace-conda
      - id: end-of-file-fixer-conda
      - id: check-yaml-conda
      - id: mixed-line-ending-conda
        args:
          - --fix=lf
  - repo: https://github.com/Quantco/pre-commit-mirrors-typos
    rev: "1.16.23"
    hooks:
      - id: typos-conda
        files: "\\.(md|rst)$"
        exclude: ^niceplots/deprecated/
