name: nice-plots
channels:
  - conda-forge
dependencies:
  - python>=3.0
  - make
  - pre-commit
  - pytest>=6 # Adds --import-mode option
  - pytest-cov
  - pytest-xdist # adds distributed tests
  - pip
  - sqlfluff=2.3.5 # keep in syn w. pre-commit hook
  - nb_black
  - yaml
  - pydantic
  - matplotlib-base
  - pandas
  - seaborn
  # documentation
  - sphinx
