name: nice-plots
channels:
  - conda-forge
dependencies:
  - python>=3.0
  - make
  - pre-commit
  - pytest>=6 # Adds --import-mode option
  - pytest-cov
  - pytest-xdist # adds distributed tests
  - pip
  - pip:
      - openpyxl
  - nb_black
  - yaml
  - pydantic
  - matplotlib-base
  - pandas
  - seaborn
  - click
  - os
  - subprocess
  - platform
  - tqdm
  # documentation
  - sphinx
